# Generated by Django 4.2 on 2023-04-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Полное имя')),
                ('contacts', models.CharField(max_length=200, verbose_name='Контакты')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новый клиент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['full_name'],
            },
        ),
    ]
