# Generated by Django 4.2 on 2023-04-09 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 9, 17, 49, 41, 747716), verbose_name='Дата начала работы'),
        ),
    ]
