# Generated by Django 4.2 on 2023-04-09 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала работы'),
        ),
    ]
