# Generated by Django 4.2 on 2023-04-09 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 4, 9), verbose_name='Дата начала работы'),
        ),
    ]
