# Generated by Django 4.2 on 2023-04-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Запись обновлена')),
                ('start_date', models.DateTimeField(verbose_name='Цена действительна с')),
                ('end_date', models.DateTimeField(verbose_name='Цена действительна до')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуально?')),
                ('value', models.PositiveIntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Цены',
                'ordering': ['updated_at'],
            },
        ),
    ]
