# Generated by Django 4.2 on 2023-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='payment_per_day',
            field=models.IntegerField(default=0, verbose_name='Зарплата за день'),
        ),
    ]
