# Generated by Django 4.2 on 2023-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_dailywork_payment_per_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neworder',
            options={'verbose_name': 'Образец', 'verbose_name_plural': 'Образцы'},
        ),
        migrations.AlterField(
            model_name='neworder',
            name='color',
            field=models.CharField(max_length=25, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Стоимость'),
        ),
    ]
